#Plugin by Bleepo, Config manager by 254n_m

KickOnJoin:
  Enabled: true
  Message:
    - "&3&lL2&r&b&lX9&r"
    - "&7&m-------------------------------------------------------"
    - ""
    - "&6L2X9 is currently taking a backup, Please wait until it is finished."
    - "&6L2X9 está tomando una copia de seguridad, espere hasta que termine."
    - ""
    - "&7&m-------------------------------------------------------"

DomainRedirect:
  Enabled: true
  Message:
    - "&3&lL2&r&b&lX9&r"
    - "&7&m-------------------------------------------------------"
    - ""
    - "&6Please connect with &3l2x9.dev &6instead."
    - "&6En su lugar, conéctese con &3l2x9.dev&6."
    - ""
    - "&7&m-------------------------------------------------------"
  Domains:
    - "domain1.xyz"
    - "domain2.xxx"
    - "etc.lol"